version: '3'

services:
  oauth2-server:
    container_name: oauth2-server
    image: aaronpederson/oauth2-server
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - REDIRECT_URI=https://client.example.com/callback
    ports:
      - "3000:3000"
    restart: always

  oauth2-client:
    container_name: oauth2-client
    image: aaronpederson/oauth2-client
    environment:
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - REDIRECT_URI=https://client.example.com/callback
      - AUTHORIZATION_URI=http://oauth2-server:3000/authorize
      - TOKEN_URI=http://oauth2-server:3000/token
      - SCOPE=email
    ports:
      - "8080:8080"
    restart: always
