version: '3.7'

services:
  # Jaeger components
  jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    container_name: jaeger-agent
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=5775
    ports:
      - "5775:5775/udp"  # Agent port (used by the client libraries)
    networks:
      - observability

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    container_name: jaeger-collector
    environment:
      - COLLECTOR_ZIPKIN_HTTP_HTTP_PORT=9411
    ports:
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "14267:14267"
    networks:
      - observability

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger-query
    environment:
      - QUERY_BASE_PATH=/jaeger
    ports:
      - "16686:16686"  # Jaeger UI
    networks:
      - observability

  # Prometheus for monitoring metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus config file
    ports:
      - "9090:9090"  # Prometheus UI
    networks:
      - observability

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
    ports:
      - "3000:3000"  # Grafana UI
    networks:
      - observability
    depends_on:
      - prometheus

networks:
  observability:
    driver: bridge
