global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger-collector:5775', 'jaeger-query:16686']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
