version: '3'

services:
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: http://grafana:3000
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
