version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.20-alpine
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always

  nginx-exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    restart: always
    command: ["nginx-prometheus-exporter", "-nginx.scrape-uri", "http://nginx:80/status", "-web.telemetry-path", "/metrics", "-web.listen-address", ":9113", "-prometheus-url", "http://prometheus:9090/"]

  cli:
    container_name: nginx_centos7
    image: centos:7.9.2009
    stdin_open: true
    tty: true
    command: /bin/bash

  amplify:
    container_name: nginx_amplify
    image: nginxinc/nginx-amplify:2.2.0
    environment:
      - AMPLIFY_IMAGENAME=nginx
      - AMPLIFY_API_KEY=<your_api_key>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8010:80"  # Change the port from 80 to 8010
    restart: always
