version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    restart: always
    ports:
      - "8050:8080"
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebook
      - ZEPPELIN_CONF_DIR=/zeppelin/conf
      - accumulo.instance.name=my-instance-name
      - accumulo.zookeeper.host=zookeeper:2181
      - accumulo.username=my-username
      - accumulo.password=my-password
    volumes:
      - ./notebooks:/zeppelin/notebook
      - ./conf:/zeppelin/conf
