version: '3'

services:
  solr:
    hostname: solr
    container_name: solr
    image: solr:9.4
    ports:
      - "8983:8983"
    volumes:
      - solr_config:/opt/solr/server/solr/configsets/my_custom_config
      - solr_logs:/opt/solr/server/logs
      - solr_data:/var/solr/data
    networks:
      - solr-net
    # command: /opt/solr-9.4.1/prometheus-exporter/bin/solr-exporter

networks:
  solr-net:

volumes:
  solr_config:
  solr_logs:
  solr_data:


    # HOW TO RUN MULTIPLE COMMANDS

    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     chmod +x /opt/solr-9.4.1/prometheus-exporter/bin/solr-exporter && \
    #     /opt/solr-9.4.1/prometheus-exporter/bin/solr-exporter
