version: "3.8"

services:
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.8.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    kafka-exporter:
      image: danielqsj/kafka-exporter:v1.2.0
      ports:
        - "9308:9308"
      environment:
        KAFKA_SERVER: kafka:9092
        JMX_PORT: 9999
