version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.2.2
    ports:
      - "9100:9100"
    restart: always
